package(default_visibility = ["//visibility:public"])

proto_library(
    name = "firrtl_proto",
    srcs = ["firrtl.proto"],
)

java_proto_library(
    name = "firrtl_java_proto",
    deps = [":firrtl_proto"],
)

